name: ConsoleChat
version: 1.0.2
main: org.eu.codezhangborui.consolechat.ConsoleChat
author: CodeZhangBorui
description: 优化在后台终端的聊天信息
commands:
  cc:
    description: 发送后台信息
    usage: /cc <message>
    permission: consolechat.chat
    permission-message: 你没有权限执行此命令
  setconsoler:
    description: 设置当前后台使用者
    usage: /getcon <username>
    permission: consolechat.setconsoler
    permission-message: 你没有权限执行此命令
  getconsoler:
    description: 查看已设置的当前后台使用者
    usage: /getconsoler
    permission: consolechat.getconsoler
    permission-message: 你没有权限执行此命令
  delconsoler:
    description: 移除已设置的当前后台使用者
    usage: /delconsoler
    permission: consolechat.delconsoler
    permission-message: 你没有权限执行此命令
    